#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web. 
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

declare -A URLS

URLS=(
  ["google"]="https://www.google.com/search?q="
)

# List for rofi
gen_list() {
    for i in "${!URLS[@]}"
    do
      echo "$i"
    done
}

main() {
  # Pass the list to rofi
  #platform=$( (gen_list) | rofi -dmenu -fuzzy -only-match -location 0 -p "Search > " )

  query=$( (echo ) | rofi  -dmenu -fuzzy -location 0 -p "Google > " )
  if [[ -n "$query" ]]; then
    url=${URLS["google"]}$query
    xdg-open "$url"
  else 
    rofi -show -e "No query provided."
  fi
}

main 

exit 0
